// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcq7fpPbeGXFo5d24t7HOpP7j7MI5rjc',
    appId: '1:441522416299:web:fd367b115ae2276d6b25ee',
    messagingSenderId: '441522416299',
    projectId: 'sortack-xai304-345a',
    authDomain: 'sortack-xai304-345a.firebaseapp.com',
    storageBucket: 'sortack-xai304-345a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9ELfE9CzLQvPjCRukep634aquYnNkCs',
    appId: '1:441522416299:android:d18aa248a957a2dc6b25ee',
    messagingSenderId: '441522416299',
    projectId: 'sortack-xai304-345a',
    storageBucket: 'sortack-xai304-345a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneBSQ4X5YC_U3KeVlLqreNXy2DAYw8Jw',
    appId: '1:441522416299:ios:b0121b73a0ad3f536b25ee',
    messagingSenderId: '441522416299',
    projectId: 'sortack-xai304-345a',
    storageBucket: 'sortack-xai304-345a.firebasestorage.app',
    iosBundleId: 'com.example.sortack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBneBSQ4X5YC_U3KeVlLqreNXy2DAYw8Jw',
    appId: '1:441522416299:ios:b0121b73a0ad3f536b25ee',
    messagingSenderId: '441522416299',
    projectId: 'sortack-xai304-345a',
    storageBucket: 'sortack-xai304-345a.firebasestorage.app',
    iosBundleId: 'com.example.sortack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKcq7fpPbeGXFo5d24t7HOpP7j7MI5rjc',
    appId: '1:441522416299:web:d4e70f398c3af0e26b25ee',
    messagingSenderId: '441522416299',
    projectId: 'sortack-xai304-345a',
    authDomain: 'sortack-xai304-345a.firebaseapp.com',
    storageBucket: 'sortack-xai304-345a.firebasestorage.app',
  );
}
